
import plistlib
from pathlib import Path

from models import ItunesPlaylist, ItunesPlaylistTrack, ItunesTrack
from utils import normalize_artist


# System playlists are auto-generated by iTunes and do not represent
# user curation decisions. Any playlist whose name appears here or
# whose Master/Visible flags mark it as a system list gets filtered out.
# This is defined at the module level because it is a constant --
# it never changes at runtime and does not belong inside a function.
SYSTEM_PLAYLIST_NAMES = {
    "Music", "Music Videos", "Purchased", "Genius",
    "Recently Added", "Recently Played", "Top 25 Most Played",
    "My Top Rated", "Voice Memos", "Rentals", "Movies",
    "TV Shows", "Home Videos", "Apps", "Books", "PDFs",
    "Audiobooks", "iTunes U"
}


def load_itunes_data(path: Path) -> dict:
    """
    Load the iTunes XML library file and return the raw library dictionary.
    :param path: Path to iTunes_Music_Library.xml
    :return: Full library dict as parsed by plistlib
    """
    with open(path, "rb") as f:
        return plistlib.load(f)




def convert_to_itunes_track(track_dict: dict) -> ItunesTrack | None:
    """
    Map a single raw plist track dictionary to an ItunesTrack dataclass.
    :param track_dict: One track entry from the plist Tracks dictionary
    :return: Populated ItunesTrack dataclass
    """
    artist = track_dict.get("Artist")
    play_date   = track_dict.get("Play Date UTC")
    last_played = play_date.isoformat() if play_date else None

    added_date = track_dict.get("Date Added")
    date_added = added_date.isoformat() if added_date else None

    try:
        itunes_track = ItunesTrack(
            track_id = track_dict["Track ID"],
            name = track_dict["Name"],
            artist = artist,
            album = track_dict.get("Album"),
            genre= track_dict.get("Genre"),
            duration_ms = track_dict.get("Stop Time", 0) or track_dict.get("Total Time", 0),
            year= track_dict.get("Year"),
            play_count= track_dict.get("Play Count", 0),
            skip_count= track_dict.get("Skip Count", 0),
            last_played= last_played,
            date_added= date_added,
            artist_normalized = normalize_artist(artist)
        )

    except KeyError as e:
        # THIS is your Dead-Letter Queue in action.
        # You write the bad data somewhere else, and don't stop the program.
        print(f"Failed to parse track, missing key {e}. Writing to error log...")
        with open("malformed_itunes_data.log", "a") as error_log:
            error_log.write(f"Missing {e} in data: {track_dict}\n")
        return None

    return itunes_track


def process_itunes_tracks(library: dict) -> list[ItunesTrack | None]:
    """
    Extract and convert all tracks from the library dictionary.
    :param library: Full library dict returned by load_itunes_data
    :return: List of ItunesTrack dataclasses ready for insertion
    """
    itracks = library.get("Tracks", {})
    results = [convert_to_itunes_track(t) for t in itracks.values()]
    print(f"  Parsed {len(results)} iTunes tracks from library")
    return results


def is_system_playlist(playlist: dict) -> bool:
    """
    Return True if this playlist is system-generated and should be skipped.
    :param playlist: One playlist entry from the plist Playlists list
    :return: True if the playlist should be excluded
    """
    return (
        playlist.get("Master") is True or
        playlist.get("Visible") is False or
        playlist.get("Name", "") in SYSTEM_PLAYLIST_NAMES
    )


def convert_to_playlist(
    playlist_dict: dict,
) -> tuple[ItunesPlaylist, list[ItunesPlaylistTrack]]:
    """
    Convert a single playlist dict into an ItunesPlaylist and its track memberships.
    :param playlist_dict: One playlist entry from the plist Playlists list
    :return: Tuple of (ItunesPlaylist, list of ItunesPlaylistTrack)
    """
    itunesPlaylist = ItunesPlaylist(
        playlist_id=playlist_dict["Playlist ID"],
        name= playlist_dict.get("Name")
    )

    playlist_items = playlist_dict.get("Playlist Items", [])
    itunesPlaylistTracks = [
        ItunesPlaylistTrack(
            playlist_id=itunesPlaylist.playlist_id,
            itunes_track_id=item["Track ID"]
        )
        for item in playlist_items
    ]
    return itunesPlaylist, itunesPlaylistTracks


def process_itunes_playlists(
    library: dict,
) -> tuple[list[ItunesPlaylist], list[ItunesPlaylistTrack]]:
    """
    Extract and convert all user-created playlists from the library dictionary.
    :param library: Full library dict returned by load_itunes_data
    :return: Tuple of (list of ItunesPlaylist, flat list of ItunesPlaylistTrack)
    """
    # filter it using is_system_playlist -- keep only playlists where it returns False
    user_playlists = [
        pl for pl in library.get("Playlists", []) 
        if not is_system_playlist(pl)
    ]
    
    playlists = []
    playlist_tracks = []

    for pl_dict in user_playlists:
        pl, track = convert_to_playlist(pl_dict)
        playlists.append(pl)
        playlist_tracks.extend(track) 

    return playlists, playlist_tracks 